FROM solr:8.3.1 
LABEL maintainer="Joel Farthing <joel.farthing@usask.ca>"

USER solr:solr

ENV CONF_SETS /opt/solr/server/solr/configsets

# Copy the Solr /conf from the GeoBlacklight repo
COPY --chown=solr:solr ./solr/conf ${CONF_SETS}/geoblacklight/conf

CMD ["solr","start","-f"]
