FROM solr:8.3.1

LABEL maintainer="Joel Farthing <joel.farthing@usask.ca>"

USER solr

ENV PATH /opt/solr/bin:${PATH}
ENV SOLR_HOME /var/solr/data/
ENV GEO_CORE ${SOLR_HOME}/geoblacklight/

RUN mkdir -p ${GEO_CORE}

#ADD --chown=solr:solr solr/solr.xml ${SOLR_HOME}

# Copy the Solr config from the GeoBlacklight repo
COPY --chown=solr:solr ./solr/conf ${GEO_CORE} 

# Add start-up script
#ADD ./solr/start.sh /opt/solr-8.3.1/start.sh

VOLUME ["/var/solr"]

CMD ["solr","start","-f"]
